### ISSUE TITLE
determine common use cases to add to v2

### ISSUE THREAD

**Issue by abreksa4** [abreksa4/wikidrain#6]
Rewriting this project, would like to get feedback on uses cases and issues to better re-work the thing.

**Comment by shapito27** [comment]
had problem with empty result in function callApi()
solved problem by adding curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);

**Comment by abreksa4** [comment]
@shapito27 thanks, I'll take a look at that. 

Do you mind sharing the specific request you made (if you remember)?
